name: Comment when opened
on:
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - run: gh issue create -t "auto issue" --body "Thank you for opening this issue!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
