name: Comment when opened
on:
  workflow_dispatch:
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue create -t "auto issue" --body "Thank you for opening this issue!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
